
title: "Mark Collins"
name: "Mark Collins"
description: "Senior Lead Engineer | Cloud | Automation | Cybersecurity"
email: mark.allen.collins1@gmail.com
url: "https://mark-collins.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages
