
title: "Mark Collins"
name: "Mark Collins"
description: "Senior Lead Engineer | Cloud Computing | Automation | Cybersecurity"
email: mark.allen.collins1@gmail.com
baseurl: ""
url: "https://mark-collins.github.io"
github_username: MA01R
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
markdown: kramdown
highlighter: rouge
include: ["_pages"]
